# Generated by Django 3.1 on 2020-08-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='function',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
