# Generated by Django 3.1 on 2020-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0002_case_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_tucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('remark', models.CharField(max_length=1000, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
