# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\China\T01setUp\T01cnClientLogin.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT01Cnclientlogin(HttpRunner):

    config = (
        Config("request methods testcase with functions")
        .variables(
            **{
                "username": "${getEnvInfo(pp,cnPrimaryUserAccount)}",
                "subUser": "${getEnvInfo(${ENV(TESTENV)},cnClientSubuser)}",
            }
        )
        .base_url("http://mall.ectpp.opsmart.cn")
        .verify(False)
        .export(*["cnPrimaryUserToken", "cnSubUserToken"])
    )

    teststeps = [
        Step(
            RunRequest("get login captcha")
            .get("/api/common/captcha/image")
            .with_params(**{"d": "${getTimestamp()}"})
            .with_headers(
                **{
                    "Content-Type": "django_language=zh-cn; sessionid=w5187f5339p3dfsh94jwfmgsxao9upb0; cookiePolicy=Accepted; cookiePreference=Accepted; Hm_lvt_bdc73221fdeefe6cc0a4e8172e37c0a5=1607653582,1607737750,1607942362,1607942783; ECTIMGCAPTCHA=c51157c3-7617-4a87-ba06-cdd7dcca37c8; Hm_lpvt_bdc73221fdeefe6cc0a4e8172e37c0a5=1607949473"
                }
            )
            .extract()
            .with_jmespath("cookies.ECTIMGCAPTCHA", "returnCookie")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("primary User Login")
            .post("/api/admin/user/login")
            .with_params(**{"username": "$username", "password": "Ect2020!!"})
            .with_headers(
                **{
                    "ECTIMGCAPTCHA": "$returnCookie",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .extract()
            .with_jmespath('headers."X-Auth-Token"', "cnPrimaryUserToken")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("subUser Login")
            .post("/api/admin/user/login")
            .with_params(**{"username": "$subUser", "password": "Ect2020!!"})
            .with_headers(
                **{
                    "ECTIMGCAPTCHA": "$returnCookie",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .extract()
            .with_jmespath('headers."X-Auth-Token"', "cnSubUserToken")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseT01Cnclientlogin().test_start()
