# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\China\T01setUp\T02cnAdminLogin.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT02Cnadminlogin(HttpRunner):

    config = (
        Config("request methods testcase with functions")
        .variables(
            **{
                "username": "${getEnvInfo(${ENV(TESTENV)},adminAccount)}",
                "password": "${getEnvInfo(${ENV(TESTENV)},adminPassword)}",
            }
        )
        .base_url("http://admin.ectpp.opsmart.cn")
        .verify(False)
        .export(*["cnAdminUserToken"])
    )

    teststeps = [
        Step(
            RunRequest("get admin login captcha")
            .get("/api/common/captcha/image")
            .with_params(**{"d": "${getTimestamp()}"})
            .with_headers(
                **{
                    "Content-Type": "Hm_lvt_ab44aa1c4d9b7bdf57dc3212a2d9b101=1607992854; sidebarStatus=1; Hm_lpvt_ab44aa1c4d9b7bdf57dc3212a2d9b101=1608032943"
                }
            )
            .extract()
            .with_jmespath("cookies.ECTIMGCAPTCHA", "returnAdminCookie")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("admin login")
            .post("/api/admin/internal/user/login")
            .with_params(**{"username": "$username", "password": "$password"})
            .with_headers(
                **{
                    "ECTIMGCAPTCHA": "$returnAdminCookie",
                    "Content-Type": "application/json;charset=UTF-8",
                }
            )
            .extract()
            .with_jmespath('headers."X-Auth-Token"', "cnAdminUserToken")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("admin set tenant")
            .put(
                "/api/admin/internal/user/update-internal-shared-user-by-tenant/a63727e57aaa2660e0539fe716acc5ab"
            )
            .with_headers(
                **{
                    "X-Auth-Token": "$cnAdminUserToken",
                    "Content-Type": "application/json;charset=UTF-8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseT02Cnadminlogin().test_start()
