# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\trade_group.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTradeGroup(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/common/tradegroup")
            .get("http://mall.ectpp.opsmart.cn/api/common/tradegroup")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Cookie": "django_language=zh-cn; sessionid=g8sziwvzdzfa6y20si720w5t5ynyt6g8; cookiePolicy=Accepted; cookiePreference=Accepted; Hm_lvt_bdc73221fdeefe6cc0a4e8172e37c0a5=1606368909,1606877077,1606956508,1607392408; token=4f77c858-629b-49e2-bf17-1fbc7151221b; Hm_lpvt_bdc73221fdeefe6cc0a4e8172e37c0a5=1607583571",
                    "Host": "mall.ectpp.opsmart.cn",
                    "Referer": "http://mall.ectpp.opsmart.cn/product",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "X-Auth-Token": "4f77c858-629b-49e2-bf17-1fbc7151221b",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_bdc73221fdeefe6cc0a4e8172e37c0a5": "1607583571",
                    "Hm_lvt_bdc73221fdeefe6cc0a4e8172e37c0a5": "1606368909,1606877077,1606956508,1607392408",
                    "cookiePolicy": "Accepted",
                    "cookiePreference": "Accepted",
                    "django_language": "zh-cn",
                    "sessionid": "g8sziwvzdzfa6y20si720w5t5ynyt6g8",
                    "token": "4f77c858-629b-49e2-bf17-1fbc7151221b",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
        ),
    ]


if __name__ == "__main__":
    TestCaseTradeGroup().test_start()
