insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'APTD',''  from company where sapid='1188968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'LATD',''  from company where sapid='1188968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'ETD',''  from company where sapid='1188968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'ATD',''  from company where sapid='1188968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'PANASIA',''  from company where sapid='1188968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'COSCON S.E.A',''  from company where sapid='1188968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'APTD','IAG'  from company where sapid='1188968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'APTD','IAR'  from company where sapid='1188968000';

insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'APTD',''  from company where sapid='1226015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'LATD',''  from company where sapid='1226015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ETD',''  from company where sapid='1226015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ATD',''  from company where sapid='1226015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'PANASIA',''  from company where sapid='1226015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'COSCON S.E.A',''  from company where sapid='1226015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'APTD','IAG'  from company where sapid='1226015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'APTD','IAR'  from company where sapid='1226015000';




insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'PANASIA','IAW'  from company where sapid='6382131000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'COSCON S.E.A',''  from company where sapid='6382131000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'PANASIA',''  from company where sapid='6382131000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ATD',''  from company where sapid='6382131000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ETD',''  from company where sapid='6382131000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'LATD',''  from company where sapid='6382131000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'APTD',''  from company where sapid='6382131000';

insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'COSCON S.E.A',''  from company where sapid='6419407000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'PANASIA',''  from company where sapid='6419407000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'ATD',''  from company where sapid='6419407000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'ETD',''  from company where sapid='6419407000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'LATD',''  from company where sapid='6419407000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'APTD',''  from company where sapid='6419407000';

insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'COSCON S.E.A',''  from company where sapid='6600006000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'PANASIA',''  from company where sapid='6600006000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'ATD',''  from company where sapid='6600006000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'ETD',''  from company where sapid='6600006000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'LATD',''  from company where sapid='6600006000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'APTD',''  from company where sapid='6600006000';


insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'COSCON S.E.A',''  from company where sapid='7012015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'PANASIA',''  from company where sapid='7012015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ATD',''  from company where sapid='7012015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ETD',''  from company where sapid='7012015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'LATD',''  from company where sapid='7012015000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'APTD',''  from company where sapid='7012015000';

insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'PANASIA','IAW'  from company where sapid='7098968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'COSCON S.E.A',''  from company where sapid='7098968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'PANASIA',''  from company where sapid='7098968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ATD',''  from company where sapid='7098968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ETD',''  from company where sapid='7098968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'LATD',''  from company where sapid='7098968000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'APTD',''  from company where sapid='7098968000';


insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'COSCON S.E.A',''  from company where sapid='7165101000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'PANASIA',''  from company where sapid='7165101000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'ATD',''  from company where sapid='7165101000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'ETD',''  from company where sapid='7165101000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'LATD',''  from company where sapid='7165101000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'APTD',''  from company where sapid='7165101000';


insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'PANASIA','IAW'  from company where sapid='7516491000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'COSCON S.E.A',''  from company where sapid='7516491000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,2,'PANASIA',''  from company where sapid='7516491000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'ATD',''  from company where sapid='7516491000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'ETD',''  from company where sapid='7516491000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'LATD',''  from company where sapid='7516491000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'APTD',''  from company where sapid='7516491000';


insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'APTD','IAR'  from company where sapid='8178189000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'APTD','IAG'  from company where sapid='8178189000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'COSCON S.E.A',''  from company where sapid='8178189000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'PANASIA',''  from company where sapid='8178189000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'ATD',''  from company where sapid='8178189000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'ETD',''  from company where sapid='8178189000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,5,'LATD',''  from company where sapid='8178189000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'APTD',''  from company where sapid='8178189000';


insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'PANASIA','IAW'  from company where sapid='7763214000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'COSCON S.E.A',''  from company where sapid='7763214000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,2,'PANASIA',''  from company where sapid='7763214000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ATD',''  from company where sapid='7763214000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ETD',''  from company where sapid='7763214000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'LATD',''  from company where sapid='7763214000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'APTD',''  from company where sapid='7763214000';


insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'LATD','TAW'  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'LATD','TAA'  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'LATD','ACA'  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'LATD','AAW'  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'LATD','AAT'  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'COSCON S.E.A',''  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'PANASIA',''  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ATD',''  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ETD',''  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'LATD',''  from company where sapid='7569987000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'APTD',''  from company where sapid='7569987000';

insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'COSCON S.E.A',''  from company where sapid='7280482000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'PANASIA',''  from company where sapid='7280482000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,1,'ATD',''  from company where sapid='7280482000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'ETD',''  from company where sapid='7280482000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'LATD',''  from company where sapid='7280482000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,4,'APTD',''  from company where sapid='7280482000';

insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'PANASIA','IAW'  from company where sapid='1087171000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'COSCON S.E.A',''  from company where sapid='1087171000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,2,'PANASIA',''  from company where sapid='1087171000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ATD',''  from company where sapid='1087171000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'ETD',''  from company where sapid='1087171000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'LATD',''  from company where sapid='1087171000';
insert into company_level_custom(uuid, create_by, create_time,update_by, update_Time, version, company_name_en, company_name_zh, company_no, effective_start,effective_end ,is_active,sap_id,sailing_level,trade_area,trade_lane )   select sys_guid(),'system', sysdate, 'system', sysdate,0, name_en, name_zh, company_no, sysdate, sysdate +180, 1, sapid ,3,'APTD',''  from company where sapid='1087171000';

update company_level_custom set effective_start = sysdate -1/3 where create_by='system' and create_time> sysdate-1 ;

COMMIT;

